import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { askRag, getRagDocuments, getRagSuggested, type RagAnswer, type RagCitation, type RagDocument } from "../lib/rag";

interface Turn {
  question: string;
  answer: RagAnswer;
}

function ModeBadge({ mode }: { mode: RagAnswer["mode"] }) {
  if (mode === "generated") {
    return (
      <span className="inline-flex items-center rounded-full bg-gold-50 px-2 py-0.5 text-xs font-medium text-gold-700 ring-1 ring-inset ring-gold-200 dark:bg-gold-950/30 dark:text-gold-400 dark:ring-gold-800">
        Generated by Claude, grounded in the excerpts below
      </span>
    );
  }
  if (mode === "extractive") {
    return (
      <span className="inline-flex items-center rounded-full bg-neutral-100 px-2 py-0.5 text-xs font-medium text-neutral-600 ring-1 ring-inset ring-neutral-200 dark:bg-neutral-800 dark:text-neutral-400 dark:ring-neutral-700">
        Retrieved passage (no live model configured for this deployment)
      </span>
    );
  }
  return (
    <span className="inline-flex items-center rounded-full bg-neutral-100 px-2 py-0.5 text-xs font-medium text-neutral-600 ring-1 ring-inset ring-neutral-200 dark:bg-neutral-800 dark:text-neutral-400 dark:ring-neutral-700">
      No match found
    </span>
  );
}

function CitationCard({ citation }: { citation: RagCitation }) {
  return (
    <div className="rounded-lg border border-neutral-200 bg-neutral-50 p-3 text-sm dark:border-neutral-800 dark:bg-neutral-900">
      <div className="flex items-baseline justify-between gap-2">
        <p className="font-medium text-neutral-800 dark:text-neutral-200">{citation.title}</p>
        <span className="shrink-0 text-xs text-neutral-500">p.{citation.page}</span>
      </div>
      <p className="mt-1 text-neutral-500 dark:text-neutral-400">&ldquo;{citation.snippet}&rdquo;</p>
      <div className="mt-2 flex flex-wrap gap-3 text-xs">
        <a href={citation.pdfHref} target="_blank" rel="noreferrer" className="font-medium text-gold-700 hover:underline dark:text-gold-400">
          Open PDF at p.{citation.page} &rarr;
        </a>
        <Link to={citation.projectHref} className="font-medium text-gold-700 hover:underline dark:text-gold-400">
          View write-up page &rarr;
        </Link>
      </div>
    </div>
  );
}

function TurnCard({ turn }: { turn: Turn }) {
  return (
    <div className="rounded-xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900">
      <p className="text-sm font-semibold text-neutral-900 dark:text-neutral-100">{turn.question}</p>
      <div className="mt-2">
        <ModeBadge mode={turn.answer.mode} />
      </div>
      <p className="mt-3 text-sm leading-relaxed text-neutral-700 dark:text-neutral-300">{turn.answer.answer}</p>
      {turn.answer.citations.length > 0 && (
        <div className="mt-4 space-y-2">
          <p className="text-xs font-medium uppercase tracking-wide text-neutral-500">Sources</p>
          {turn.answer.citations.map((c, i) => (
            <CitationCard key={i} citation={c} />
          ))}
        </div>
      )}
    </div>
  );
}

export default function ResearchAssistant() {
  const [documents, setDocuments] = useState<RagDocument[]>([]);
  const [suggested, setSuggested] = useState<(RagAnswer & { question: string })[]>([]);
  const [turns, setTurns] = useState<Turn[]>([]);
  const [question, setQuestion] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    getRagDocuments().then((r) => setDocuments(r.documents)).catch(() => {});
    getRagSuggested().then((r) => setSuggested(r.suggested)).catch(() => {});
  }, []);

  function askSuggested(item: RagAnswer & { question: string }) {
    setTurns((t) => [{ question: item.question, answer: item }, ...t]);
  }

  async function askLive(q: string) {
    const trimmed = q.trim();
    if (!trimmed) return;
    setLoading(true);
    setError(null);
    try {
      const answer = await askRag(trimmed);
      setTurns((t) => [{ question: trimmed, answer }, ...t]);
      setQuestion("");
    } catch (e) {
      setError(e instanceof Error ? e.message : "Something went wrong");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="mx-auto max-w-5xl px-6 py-10">
      <Link to="/" className="text-sm text-neutral-500 hover:text-neutral-900 dark:hover:text-neutral-100">
        &larr; All projects
      </Link>
      <h1 className="mt-2 text-2xl font-semibold tracking-tight text-neutral-900 dark:text-neutral-100">
        Research Assistant: RAG Over My Own Write-Ups
      </h1>
      <p className="mt-2 max-w-2xl text-sm text-neutral-600 dark:text-neutral-400">
        Retrieval-augmented Q&amp;A over the 10 technical write-ups on this site's{" "}
        <Link to="/deep-learning" className="font-medium text-gold-700 hover:underline dark:text-gold-400">
          Deep Learning
        </Link>{" "}
        page (555 chunks total). Retrieval is a from-scratch TF-IDF + cosine-similarity ranking over a
        precomputed index &mdash; no vector database, no LangChain. Generation calls Claude Haiku to
        synthesize a cited answer from the top-ranked passages; if no API key is configured for this
        deployment, it falls back to showing the top passage directly instead of failing.
      </p>

      <div className="mt-8 grid grid-cols-1 gap-8 lg:grid-cols-[260px_1fr]">
        <div className="space-y-6">
          <div>
            <p className="mb-2 text-sm font-medium text-neutral-700 dark:text-neutral-300">Suggested questions</p>
            <div className="space-y-1.5">
              {suggested.map((item) => (
                <button
                  key={item.question}
                  onClick={() => askSuggested(item)}
                  className="block w-full rounded-md border border-neutral-200 px-2.5 py-1.5 text-left text-xs text-neutral-600 transition hover:border-gold-300 hover:text-gold-700 dark:border-neutral-800 dark:text-neutral-400 dark:hover:border-gold-800 dark:hover:text-gold-400"
                >
                  {item.question}
                </button>
              ))}
            </div>
          </div>

          {documents.length > 0 && (
            <div>
              <p className="mb-2 text-sm font-medium text-neutral-700 dark:text-neutral-300">Indexed write-ups</p>
              <ul className="space-y-1 text-xs">
                {documents.map((d) => (
                  <li key={d.file}>
                    <Link to={d.projectHref} className="text-neutral-500 hover:text-gold-700 dark:text-neutral-500 dark:hover:text-gold-400">
                      {d.title}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>

        <div>
          <form
            onSubmit={(e) => {
              e.preventDefault();
              askLive(question);
            }}
            className="flex gap-2"
          >
            <input
              value={question}
              onChange={(e) => setQuestion(e.target.value)}
              placeholder="Ask about backprop, GANs, object detection, transformers…"
              maxLength={300}
              className="flex-1 rounded-md border border-neutral-300 bg-white px-3 py-2 text-sm text-neutral-900 placeholder:text-neutral-400 focus:border-gold-400 focus:outline-none dark:border-neutral-700 dark:bg-neutral-900 dark:text-neutral-100"
            />
            <button
              type="submit"
              disabled={loading || !question.trim()}
              className="shrink-0 rounded-md bg-neutral-900 px-4 py-2 text-sm font-medium text-white transition hover:bg-neutral-700 disabled:opacity-50 dark:bg-neutral-100 dark:text-neutral-900 dark:hover:bg-neutral-300"
            >
              {loading ? "Asking…" : "Ask"}
            </button>
          </form>
          {error && <p className="mt-2 text-sm text-red-600 dark:text-red-400">{error}</p>}

          <div className="mt-6 space-y-4">
            {turns.length === 0 && (
              <div className="flex h-40 items-center justify-center rounded-lg border border-dashed border-neutral-300 text-sm text-neutral-400 dark:border-neutral-700">
                Pick a suggested question or ask your own
              </div>
            )}
            {turns.map((t, i) => (
              <TurnCard key={i} turn={t} />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
